[package]
name = "opendal-c"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]
doc = false

[build-dependencies]
cbindgen = "0.29.0"

[dependencies]
bytes = "1.10.1"
opendal = { version = "0.53.3", features = ["layers-blocking", "services-fs"] }
tokio = "1.45.1"
